### PR TITLE
ptt_BR.lang update

### PR DESCRIPTION
**Pull request by Erikmoto**
Updated pt_BR.lang

### CODE REVIEW

**Comment by Thutmose** [comment]
This PR shows no changes, are you sure it was done correctly?

image

**Comment by Erikmoto** [comment]
Sorry, I messed it up.
I used the Desktop version and forgot to commit the files kkkkkkkkk.

**Comment by Thutmose** [comment]
No problem, I figured it was something like that :D

**Comment by Erikmoto** [comment]
I'll send the right thing right away

**Pull request closed without merging**
